# Generated by Django 4.0.2 on 2022-02-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=20)),
                ('varient', models.CharField(max_length=20)),
                ('model', models.IntegerField()),
                ('owner', models.IntegerField()),
                ('fuel', models.CharField(max_length=10)),
                ('tyre', models.CharField(max_length=10)),
                ('insurence', models.CharField(max_length=20)),
                ('FC', models.DateField()),
                ('colour', models.CharField(max_length=10)),
                ('chase_number', models.CharField(max_length=20)),
                ('engine_number', models.CharField(max_length=20)),
                ('buy_price', models.IntegerField()),
            ],
        ),
    ]
